### ISSUE TITLE
MinimigAGA 1.2 core (wording): 68010 CPU, MHz missing

### ISSUE THREAD

**Issue by AmigaIstMiST** [mist-devel/mist-binaries#10]
- Info text on OSD says: "... Minimig can emulate an 68000 or 68020 processor .."
  The 68010 cpu is missing here.
- I personally think, there should be MHz after the cpu names. What, if you combine a 68020 cpu with OCS/ECS? Will it be clocked at 7 MHz or 14 MHz? If the text would say "CPU : 68020 (14MHz)" it would be clear.

The info text also claims, that the 68020 cpu is not faster than an 68000 when using 68000 software. On the current Amiga core, 68020 is twice as fast as a 68000 using ECS/OCS (according to Sysinfo), maybe this text comes from an older version of the core.

**Comment by sleary78** [comment]
There is very little point in emulating a 68010. The only difference from a
68000 is the exception stack frame AFAIK.

On Sat, Mar 26, 2016 at 7:37 AM, AmigaIstMiST <notifications@github.com>
wrote:

>
>    -
>
>    Info text on OSD says: "... Minimig can emulate an 68000 or 68020
>    processor .."
>    The 68010 cpu is missing here.
>    -
>
>    I personally think, there should be MHz after the cpu names. What, if
>    you combine a 68020 cpu with OCS/ECS? Will it be clocked at 7 MHz or 14
>    MHz? If the text would say "CPU : 68020 (14MHz)" everything would be clear.
>
> (BTW: a 68020 CPU with more MHz (25? 28?) would be cool :-) )
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mist-devel/mist-binaries/issues/10>
>



-- 
Stephen Leary

**Comment by AmigaIstMiST** [comment]
The 68010 core is already there :-)
Only the info text is too old.

**Comment by AmigaIstMiST** [comment]
This issue is only about wording.
