### ISSUE TITLE
No Beeper Sound on ZXN Core

### ISSUE THREAD

**Issue by Julitium** [mist-devel/mist-binaries#100]
Hello.
I have been testing the core ZXN (ZXNext) and the Beeper sound does not work, the AY sound works perfectly.

Thanks a lot,
All the best

**Comment by gyurco** [comment]
I definitely hear something when I issue a BEEP 1,0 in BASIC.

**Comment by Julitium** [comment]
Hi.
You're right!!!
Maybe I didn't use the latest version. I have changed the system image to latest and it seems to work fine ...
I will continue testing !!!
Thank you very much.
Greetings
