### ISSUE TITLE
Feature request: more per core settings override sections

### ISSUE THREAD

**Issue by boomlinde** [mist-devel/mist-binaries#103]
I understand from the wiki that some cores allow settings overrides that apply to just those cores. Listed as supported are MINIMIG, ST, PACE, ARCHIE. Is it easy to extend this to more cores? My specific conundrum is that I have a Megadrive-style joypad with six face buttons (+ start and mode) and two extra shoulder buttons. I was thinking that I could comfortably use this for both the fpgagen and snes cores, but they would require different mappings.

**Comment by gyurco** [comment]
It's possible to override any [mist] setting in a [corename] section. "Corename" is in the left side of the OSD.

**Comment by boomlinde** [comment]
Thank you, that works just as I'd hoped! I appreciate the help.
