### ISSUE TITLE
FPGA64 SID Code. 

### ISSUE THREAD

**Issue by Julitium** [mist-devel/mist-binaries#106]
Hi.
After hearing many rumors (and failed tests) I have seen that @Sorgelig has included new code to implement the SID. I would like to know if it is possible to extrapolate that code to our beloved MiST version that so brilliantly updates the Great @Gyurco.
Thank you very much for your opinion and reading this query (once it is cleared it will be deleted for "mailbox hygiene".

All the best

**Comment by gyurco** [comment]
Why not? But I would prefer if someone else with more SID experience would do it. With the VIC-II it's rather obvious if the result is good or bad, with the SID, it's much more subjective.

**Comment by Julitium** [comment]
Thank you very much for your answer.
Thanks again for your work on core 64, it's absolutely great
