### ISSUE TITLE
Thanks Gyurco. 

### ISSUE THREAD

**Issue by Julitium** [mist-devel/mist-binaries#108]
Hello.

I would like to thank @gyurco for all the work he has done on all MiST cores especially on C64, Spectrum and Amstrad CPC.
Now it has surprised me again by including the CD support that I am sure will give new possibilities to existing cores (SegaCD, CD32, etc) and will open new horizons (PSX, 3DO, etc).
I would like to encourage the developer community to continue to release cores with such quality.

Thank you very much @gyurco (& develop community).

**Comment by gyurco** [comment]
I'm glad you're excited but these more advanced cores are unlikely to happen on the original MiST.

**Comment by Julitium** [comment]
Hi.
Perhaps someone will be encouraged to introduce the CD routines to core Megadrive (Mega CD) and Amiga (CD32). I think the power of MiST allows it.
Thank you again ;-) 

Greetings

**Comment by gyurco** [comment]
The FPGA might be enough, but the enormous amount of RAM bandwidth required by the MegaCD hardware looks too much for that poor single SDRAM chip.

**Comment by Julitium** [comment]
Hi.
I understand. The numbers were adjusted by the "grandmother's count" ...
if the Amiga core at full power sysinfo says it is equivalent to a 68020 @ 99Mhz, a 68000 @ 7Mhz and a 68000 @ 12 Mhz it would be possible, but I did not fall for the RAM bandwidth issue.
Ahhhggg :(
Thanks again for your work.
All the best

**Comment by alessioscand** [comment]
I finally found a way to say THANK YOU to @gyurco for the Next186 core on Mist.
Thank you man, really, thank you so much.

**Comment by gyurco** [comment]
@alessioscand You're welcome! However the hard work was not the porting, but the work of the original author. Unfortunately this work is not finished, and for me, this core is a bit of disappointment, as it's not on par in compatibility with most of the MiST cores.

**Comment by alessioscand** [comment]
@gyurco you're right, but with some tweaks this core can really become a true gem, as it already runs some early PC titles titles hard-to-manage on real hardware. Please keep it going! Thank you so much!
