### ISSUE TITLE
[Amstrad core] scanlines

### ISSUE THREAD

**Issue by bonnefoi** [mist-devel/mist-binaries#11]
Hello,

could you add support for the scanlines and for memory's sake a monochrome option ?

best regards,
Pierre-François.

**Comment by renaudhelias** [comment]
Hi,

Original scanlines CRTC option is not implemented yet (Wolfenstrad demo), but is in TODO-list.
Monochrome option added to TODO-list (TODO-list is here : http://www.cpcwiki.eu/index.php/FPGAmstrad#Effort_done)

Regards,
Renaud.

**Comment by bonnefoi** [comment]
Perfect :)

**Comment by renaudhelias** [comment]
r005.8.9 : green.

**Comment by renaudhelias** [comment]
![soleil_vert_coreamstrad](https://cloud.githubusercontent.com/assets/13655988/21698656/e0edae28-d38f-11e6-9782-d5ad658553fc.png)

**Comment by renaudhelias** [comment]
r00.5.9.2 "Les Sucres en Morceaux" - green screen

**Comment by bonnefoi** [comment]
Thank you very much and happy new year !

**Comment by renaudhelias** [comment]
About triangular pixels filter effect, it cannot be done in CoreAmstrad : Amstrad true resolution is 768x288, not 384x288. Then my 768x288 is displayed as 800x600 VGA (one pixel is one pixel), I cannot insert more pixel to reach an great effect.

... but ... something like that could be done : http://www.brunofreitas.com/node/36
![sf2](https://cloud.githubusercontent.com/assets/13655988/22371263/7dc2b22c-e496-11e6-905a-dc0f0b72ca8a.png)
![sf2sl](https://cloud.githubusercontent.com/assets/13655988/22371267/83ac4856-e496-11e6-86c6-b0334139816f.png)
One line out of two is black, or darker. Let's just have to know "how much darker".
sampling 2 pixels on this picture : (78,153,211) [darker than] (105,190,249)
105/78=1.34
190/153=1.24
249/211=1.18
(1.34+1.24+1.18)/3=1.25=5/4
4/5=0.8=0.5+0.25 (sum of two shift right : 1/2 + 1/4 or else simply another array of input/ouput)

**Comment by renaudhelias** [comment]
**Done** (finally just 1/2 darker in second lines gives good results).

Can be closed.

**Comment by renaudhelias** [comment]
![scanlines2 1](https://cloud.githubusercontent.com/assets/13655988/22404149/5acfaab8-e62b-11e6-88c7-5d30794c10fc.png)
![scanlines2](https://cloud.githubusercontent.com/assets/13655988/22404150/5c96e0f0-e62b-11e6-9702-753680ec7724.png)

**Comment by sebdel** [comment]
That's great, looks exactly like my actual CPC464 :)
If you have some bits left in the extended status register you could let people select the strength of the effect. It's very well done in the spectrum core.
