### ISSUE TITLE
Is Neo Geo core port on MiST possible ?

### ISSUE THREAD

**Issue by gkralicek** [mist-devel/mist-binaries#135]
Just wondered as Neo Geo hardware is very close to Genesis (68000 and Z80). But maybe the 32Mb module in the MiST is not enough to handle the huge ROM files from Neo Geo games.

**Comment by gyurco** [comment]
Looks like it's enough for about 140 games.
https://github.com/mist-devel/mist-binaries/tree/master/cores/neogeo

**Comment by harbaum** [comment]
Unbelievable. I was absolutely sure that this is impossible. But obviously it is possible ... You guys do magic.

**Comment by gyurco** [comment]
Your VDPSim idea for FPGAGen gave me a good start with the conversion!
