### ISSUE TITLE
OneChipMSX core still has SD card writing issues

### ISSUE THREAD

**Issue by efeist** [mist-devel/mist-binaries#14]
The last change to the Mist version of this core states the author fixed the SD writing bug. This doesn't seem to be true for me. Anytime there is an attempt from the core to write to the SD card, the computer locks up. From MSX-DOS a simple "mkdir tmp" will trigger it.

**Comment by harbaum** [comment]
Do other cores writing to the SD card work for you?

**Comment by efeist** [comment]
I leave this SD card dedicated to the MSX core since it requires FAT16. I'm going to try another card this afternoon and see if it makes a difference.

**Comment by efeist** [comment]
Yeah, prepped a brand new SanDisk card with a 2GB Fat16 partition, tried to mkdir foo and it locked up.

**Comment by sleary78** [comment]
be really useful to get a debug output from the ARM while this is
happening. Is there an rs232 port on the production MiSTs?

S.



On Wed, Apr 13, 2016 at 5:47 PM, efeist <notifications@github.com> wrote:

> Yeah, prepped a brand new SanDisk card with a 2GB Fat16 partition, tried
> to mkdir foo and it locked up.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mist-devel/mist-binaries/issues/14#issuecomment-209539309>
>



-- 
Stephen Leary

**Comment by harbaum** [comment]
I mean if _other_ cores can write to sd card

**Comment by efeist** [comment]
Well yes, the Amiga core writes fine to the FAT32 SD card it's on.

**Comment by harbaum** [comment]
Ok, then it's really the core having a problem and not the entire SD card signal chain itself. I'll have a look ...

**Comment by robinsonb5** [comment]
I haven't been able to reproduce this so far - writing seems to work OK here, but I've only tested with one card so far.  (The upstream comment about fixing SD Writes shouldn't have applied to the MIST, by the way - the issue it fixed only affected the Chameleon port.)

One thing to check - the cards you're using are definitely SD and not SDHC, yes?

**Comment by efeist** [comment]
I am embarrassed. All my SD devices are actually SDHC. I've got an actual 2GB SanDisk SD card coming from Amazon and we'll see if this solves my issues, and I assume it will. Oops..

**Comment by robinsonb5** [comment]
There's a good chance that's the problem - the OCMSX core can't handle SDHC at all (or at least, the OCMSX's BIOS can't - the BIOS itself can be loaded from SDHC just fine), and the MIST is the only platform on which you can use an SDHC even for reading, since it does translation in the firmware.  There's a warning message when you attempt to write to the SDHC in SD mode, but because the OCMSX core doesn't (yet) suppor the MIST's OSD you can't see it.  Adding support for the native OSD is on my To Do list.

**Comment by harbaum** [comment]
That's actually the reason why I don't expect the sdhc card to be the problem. But I'll take a look as well.

**Comment by robinsonb5** [comment]
I thought the SDHC -> SD translation was designed to block any attempt to write?  Is that not the case?  (The SDHC emuation must be active, because the SD BIOS on OCMSX doesn't support SHDC at all.)

**Comment by harbaum** [comment]
Ah,  indeed, we are talking about writing. Yes,  then a non-sdhc card should solve the problem. :-)

**Comment by efeist** [comment]
That was it! Regular SD card is working perfect!
