### ISSUE TITLE
SAM Coupe file are incorrectly included in this repository

### ISSUE THREAD

**Issue by mincebert** [mist-devel/mist-binaries#143]
The .rbf and .rom files in this repository for the SAM Coupe (https://github.com/mist-devel/mist-binaries/tree/master/cores/samcoupe) appear to be an HTML file, not the binary files in the original repository at https://github.com/sorgelig/SAMCoupe_MIST/tree/master/releases

Obviously, they don't work, but changing them for the files in the original repository works fine.

**Comment by gyurco** [comment]
Thanks, seems nobody noticed it for 2 years :)
