### ISSUE TITLE
how long is too long?

### ISSUE THREAD

**Issue by jotego** [mist-devel/mist-binaries#150]
It looks like the last update using the .upg file has been running for 30 minutes. Is my MiST already dead? I am afraid to turn it off...

**Comment by gyurco** [comment]
Then you're already doomed :)
https://github.com/mist-devel/mist-binaries/tree/master/firmware#important-note

But with SAM-BA or BOSSA, it's easy to recover.

**Comment by jotego** [comment]
Blast! I'll try the SAM-BA procedure. If I can fix that, I'll upgrade the SiDi too. For now, I won't try upgrading the SiDi. Thanks!
