### ISSUE TITLE
c16 core - Giana Sisters doesn't work :(

### ISSUE THREAD

**Issue by micv2** [mist-devel/mist-binaries#153]
Hi,

The new game Giana Sisters won't load 😒

https://plus4world.powweb.com/software/Giana_Sisters

Greetings,
MiC

**Comment by micv2** [comment]
Thanks gyurco 👍

With new c16 release works now

https://github.com/mist-devel/mist-binaries/blob/master/cores/c16/c16_240405.rbf

**Comment by gyurco** [comment]
Great!
