### ISSUE TITLE
Handling of index=2 (NVRAM) when needed for booting up

### ISSUE THREAD

**Issue by jotego** [mist-devel/mist-binaries#154]
Some games require a default NVRAM configuration in order to boot up properly. This is how the NVRAM is handled in MRA files:

- An `<nvram index="2">` element determines the IOCTL index to use when transferring the NVRAM contents
- An optional `<rom index="2">` element can be used to provide default contents for the NVRAM, when there is no file in the SD card for it. Note that this `<rom>` element can take direct data or a zip file and `<part>` elements, like the main ROM section at index zero

On MiST, you need a **.RAM** file present in the SD card to make the transfer happen. Currently, I have modified the **jtframe** tool to create these **.RAM** files. But I wonder if you would like to make some arrangements so users do not need to carry **.RAM** files around. Maybe the **.ARC** file could keep a copy of the default contents, or the **mra** tool could create the **.RAM** by parsing the `<rom index="2">` elements.

Some games that require a valid **.RAM** file:

- Sunset Riders
- Konami's X-Men
- Turtles in Time
- The Simpsons (only to boot with attract mode sound enabled/stereo mode)

**Comment by gyurco** [comment]
Adding the .RAM creation to the MRA tool makes sense. But I think index=2 is used for other purposes in other (MiSTer) arcade cores. Some MRAs I saw is using nvram index=.. tags, not rom ones.

**Comment by jotego** [comment]
> nvram index=.. tags

what do you mean by this?

**Comment by gyurco** [comment]
Just wandering why the default value cannot be put there:
https://github.com/jotego/jtbin/blob/01a4317734f07209c2cce71c59627707b7262f13/mra/Splatter%20House%20(World%2C%20new%20version%20(SH3)).mra#L109

Example:
```
<nvram index="2" size="63552">
01 02 03 04
</nvram>

**Comment by jotego** [comment]
MiSTer didn't read that when I worked on this. Maybe things have changed.

**Comment by gyurco** [comment]
Well, that's a pity. It would be a clean solution.

**Comment by jotego** [comment]
[This is the original discussion](https://github.com/MiSTer-devel/Main_MiSTer/issues/637) we had in a MiSTer issue. As the `<rom>` method works, it was decided not to implement it as part of `<nvram>`.

The implementation for the mra tool can leverage this too: if an nvram element exists and has the same index as a rom element, then dump the rom element as .RAM

**Comment by gyurco** [comment]
I added .RAM file generation to the MRA tool. Now it creates 43 RAM files from the current jtbin repo.

**Comment by jotego** [comment]
Thank you!
