### ISSUE TITLE
NTSC mode broken in fpga64_c1541_160110.rbf

### ISSUE THREAD

**Issue by EricGus** [mist-devel/mist-binaries#16]
NTSC mode seems broken in core fpga64_c1541_160110.rbf 

previous core fpga64_c1541_150722_r1216.rbf NTSC mode works correctly..

Problem: Using  fpga64_c1541_160110 core version, when switching to NTSC mode (from PAL default) display is disabled/goes black (tested on a variety of monitors / monitors where NTSC works on previous core).. 

tested using MiST firmware version firmware_160324

**Comment by AmigaIstMiST** [comment]
I can confim this, just a black screen when switching to ntsc. Only pal is usable.

**Comment by efeist** [comment]
Also can confirm

**Comment by sorgelig** [comment]
fixed

**Comment by efeist** [comment]
THANK YOU!
