### ISSUE TITLE
minimig-mist-1_1_20160125 AGA: USB-keyboard problem

### ISSUE THREAD

**Issue by tohe73** [mist-devel/mist-binaries#27]
EDIT: as a novice Mist user - didn't realize that earlier bug was 'corrected' by mist.ini, so issue is just stupid user not new firmware :)

I just installed new firmware and core (20160125) and noticed that my USB keyboard generates wrong key-codes when pressing 'a' or 'b' -> so pressing key 'a' -> generates 'b' and from key 'b' -> 'a'. 

With older firmware and core these seem to work. 

edit: it seems to be firmware issue as same happens with C64 core.

**Comment by Newsdee** [comment]
Have you tried the very latest firmware, 20160626?

**Comment by tohe73** [comment]
Yes, I though that would solve the issue but no...
