### ISSUE TITLE
FPGA64 - Frantic Freddie corrupts image after hitting the start button to start playing.

### ISSUE THREAD

**Issue by raparici** [mist-devel/mist-binaries#36]
I don't know if this game ever worked before in FPGA64. The issue happens with the current core and fw as of today 27/12/2016. AFAIK this game uses some mirrors for SID at least that prevent it sounding in a C128 (in 64 mode) but the MIST starts playing sound and rendering the images perfectly until the button is hit.

**Comment by gyurco** [comment]
Just two years, and the bug is fixed.
