### ISSUE TITLE
Amiga AGA: support for higher resolutions.

### ISSUE THREAD

**Issue by sorgelig** [mist-devel/mist-binaries#4]
I've thought in scandoubler mode i will get progressive mode from "Laced" modes in Workbench, but to my surprise i still see flickering screen. 
Why don't convert interlaced modes into progressive while using scandoubler? 
And what stops Amiga AGA using higher VGA modes since MIST natively support VGA?

**Comment by sleary78** [comment]
The scandoubler needs to store a full frame buffer for the deinterlaced mode for this to work. 2 line scandoubling doesn't work for deinterlacing because adjacent lines are a frame apparr

**Comment by sleary78** [comment]
Appart even. Damn autocorrect

**Comment by sorgelig** [comment]
If i remember correct I was using progressive modes on A1200 with Amiga monitor.
So, at least can enable those hires progressive modes in WB.

**Comment by harbaum** [comment]
The progressive modes are present in the 1.2 core and they do work. Just today I submitted a fix for the osd in these "productivity modes".
