### ISSUE TITLE
[CoreDocApple2 / PlusToo] 15khz support

### ISSUE THREAD

**Issue by aixtreem** [mist-devel/mist-binaries#49]
Hello,
To the respective core developpers: Is it possible to add 15khz support ?
would be great as many users run on CRT monitors

thanks!

**Comment by harbaum** [comment]
CRT screens don't necessarily need 15khz. In fact the vast majority of old VGA screens doesn't support 15khz. Only old TVs and those C64/Atari ST/Amiga screens do.

Anyway, adding 15 khz to the PlusToo isn't possible as the MAC itself didn't support that video format back in the days. The Apple2 on the other hand could likely support 15khz.

**Comment by aixtreem** [comment]
thanks for your reply, didn't know for the macintosh.
and yes, sorry, CRT is philips/tv/amiga/atari monitors in my mind :)
