### ISSUE TITLE
scrolling OSD message does sucks

### ISSUE THREAD

**Issue by renaudhelias** [mist-devel/mist-binaries#52]
It's like having to read the fucking manual in live.
And isn't nice while capturing the screen.

Add the keybjoystick option in mist.ini instead ?

**Comment by renaudhelias** [comment]
And if another want to contact me about...
* making a FPGA DAC dog ear compatible, so fine that while playing a duck gun game some ducks does come bottom front of our window...
* ... and stupid thing like displaying a VGA output 72Hz 800x600  display using FPGA VRAM...

**Comment by harbaum** [comment]
This is a community project and you have write access to the repositories :-)

Actually these scrolling texts were there in the Minimig and i removed them for the MIST as i also didn't enjoy them too much. Some re-inserted them which is totally fine as i am not the one to decide such things alone.
