### ISSUE TITLE
Sorgelig please don't abandon Mist support :(

### ISSUE THREAD

**Issue by lroby74** [mist-devel/mist-binaries#57]
Hello Sorgelig,
sorry if i write you in this way but i don't know how i can do it in other ways..

I am asking you about don't abandon Mist support, on updatings his cores..

I love this device a lot and i am very afraid that without you, support for this one may die

Thank you very much and forgive me
Best regards from Italy
Roberto Lari

**Comment by jotego** [comment]
I totally agree. We miss @sorgelig magic!

**Comment by sorgelig** [comment]
You have Gyurco who is very active on MiST. We often cooperate in cores improvements.
Jotego also can do much more than pretend :)

**Comment by jotego** [comment]
Ok. Ok. I'll release one core for MiST this week!

**Comment by harbaum** [comment]
That's great.

Anyway, there are many people who might be asked. E.g .the makers of the mistica and the mini st clones have imho never contributed anything. It may make sense to ask them as this would of course be for their own benefit.

**Comment by gyurco** [comment]
But mistica is mostly unusable for development :)

**Comment by jotego** [comment]
Why is mística unusable for development?

**Comment by gyurco** [comment]
Does it have a JTAG connector?

**Comment by lroby74** [comment]
I don' know that

Il giorno mer 30 gen 2019, 10:15 gyurco <notifications@github.com> ha
scritto:

**Comment by jotego** [comment]
I checked with the author of the board. No, it doesn't have JTAG
connectors. Good for users anyway!

**Comment by gyurco** [comment]
But imagine...no MiST will sell because of cheap clones without JTAG. You cannot get a MiST after a while. No developer can join. MiST dead.

**Comment by sorgelig** [comment]
Not every dev use JTAG, actually.
Jotego got JTAG just couple days ago. 
The author of SNES also didn't use JTAG till may be 1 month ago.

**Comment by gyurco** [comment]
Jotego is professional, he can write simulations for everything :)
My personal experience that using USB-Blaster is like drilling holes to the wall with hand or an electric drill.
