### ISSUE TITLE
C16 Core, two new games are not working properly.

### ISSUE THREAD

**Issue by micv2** [mist-devel/mist-binaries#65]
I have two new games that unfortunately do not work.
1) Alpharay has graphics errors, it is unplayable.
2) Adventure Park starts with black screen.
I do not know if I'm right here .. Please a Core Fix :)

**Comment by gyurco** [comment]
Please try 190921 release.

**Comment by micv2** [comment]
Hello, have tried it, it works :) Thank you :) 
Have a nice day!

MiC

**Comment by gyurco** [comment]
Great!
