### ISSUE TITLE
[Minimig Core AGA] don't boot with hdf file since core _minimig_mist_20191005

### ISSUE THREAD

**Issue by SheldonRetrogaming** [mist-devel/mist-binaries#66]
Hello,

Since core _minimig_mist_20191005, minimig core don't boot on hdf file
with core _minimig_mist-20190418 : work well and boot every time.

Best Regards

**Comment by gyurco** [comment]
Try to:
- Set up some slow RAM
- Delete and re-save MINIMIG.CFG

**Comment by SheldonRetrogaming** [comment]
try with 0,5Mo Slow ram : it works but less chip ram now 1,5Mo instead 2Mo.
All icones positions are lost.
workaround solution.
i will try Delete and re-save MINIMIG.CFG

**Comment by SheldonRetrogaming** [comment]
It works after delete and re-configure MINIMIG.CFG and without slow RAM.
Pinball illusion works now !!!
For me thise issue is closed.
Thank you very much for your help.
