### ISSUE TITLE
Lately ZX Spectrum cores sound like sh*t!

### ISSUE THREAD

**Issue by palehub** [mist-devel/mist-binaries#78]
The title sums it up.

Cheers.

**Comment by harbaum** [comment]
Sorry, but that's not the tone to motivate someone else to spend some hours fixing something for you.

**Comment by palehub** [comment]
Wrong.
I didn't ask anybody to spend some hours to fix anything for me. I simply stated a fact.
Nor do I pretend to motivate anyone.

Cheers.
