### ISSUE TITLE
Real ColecoVision controller unsupported on MiST DB9 port in Coleco core

### ISSUE THREAD

**Issue by famiclone6502** [mist-devel/mist-binaries#83]
Only the directions and one of the two action buttons are supported for plugging up a real ColecoVision controller. None of the number pad keys are recognized. I did not test these, but additionally the Rollerball and Super Action Controller (spinner and 2 additional action buttons) functionality are assumed to be currently unsupported in the ColecoVision core. 

[Here](http://www.chromesphere.net/coleco/Controller_Interface.html) is some technical information about the controller that may help.

I was able to use the Coleco core to repair a directional pad using a controller test program, but I was not able to see if I fixed the secondary button or number pad.

**Comment by gyurco** [comment]
Of course it's not supported. The pinout differs from the Atari DB9 joystick.

**Comment by famiclone6502** [comment]
I apologize, I did not realize it was physically impossible to implement. I wasn't sure how it was connected to the FPGA under the hood. 

Closing.

**Comment by gyurco** [comment]
It's not connected to the FPGA at all, it's connected to the ARM MCU.

**Comment by famiclone6502** [comment]
I'm interpreting that it isn't technically possible.

**Comment by gyurco** [comment]
I don't know, one have to investigate the connections and change the firmware accordingly.

**Comment by famiclone6502** [comment]
If it is technically possible, I will re-open.

**Comment by gyurco** [comment]
As pin 8 is NC, I don't think it's possible.

**Comment by robinsonb5** [comment]
Worse still, pin 7 is common, which means any direction or button on a Colecovision controller will short the MiST's +5v line to ground.  You're going to need a wiring adapter, otherwise the magic smoke is going to escape.

**Comment by gyurco** [comment]
I found this:
https://i1.wp.com/www.retronicdesign.com/wp-content/uploads/2014/11/ColecoController.jpg
I don't see pin 7 connected, so it might be safe. Just won't work.

**Comment by famiclone6502** [comment]
That one is a good reference, it's the same as [this](http://atarihq.com/danb/files/ColecoController.pdf). If pin 7 isn't physically connected on MiST and it's used by the Coleco controller, then it won't work. 

Thanks for investigating.
