### ISSUE TITLE
MinimigAGA 1.2: strange dots (graphic issue)

### ISSUE THREAD

**Issue by AmigaIstMiST** [mist-devel/mist-binaries#9]
![20160324_204649](https://cloud.githubusercontent.com/assets/17943849/14029415/4b9d81d2-f202-11e5-956e-67d56ddb0ca9.jpg)
![20160324_204247](https://cloud.githubusercontent.com/assets/17943849/14029429/5bd19246-f202-11e5-879c-bac8ad7c7b44.jpg)
![20160324_204228](https://cloud.githubusercontent.com/assets/17943849/14029441/6a6281b2-f202-11e5-8622-147f9cdf45bb.jpg)

**Comment by AmigaIstMiST** [comment]
I noticed that there are strange dots on GURUs and on the Kickstart 2.0 start screen.
I sadly do not own a real Amiga any more (I sold it and bought a PC for it, I admit it), but I can't remember having seen these dots. When the red guru rectangle is visible, there is also a surplus dot on the left lower side. When the rectangle is not visible, there is a single red dot visible.

**Comment by AmigaIstMiST** [comment]
Tested this with Kickstart 2.0/3.1 ECS/OCS.
Kickstart 1.x doesn't have this problem. I didnt't verify this with UAE, I will try to do it in a few days and will report the results here.

**Comment by AmigaIstMiST** [comment]
On UAE Kickstart 2.0 startscreen looks fine, no white dot visible (I didn't check gurus).

**Comment by AmigaIstMiST** [comment]
https://github.com/rkrajnc/minimig-mist/issues/38

**Comment by renaudhelias** [comment]
If the dot disappears after unplug/stop plateform during one day long, it's then certainly due to a memory zone not initialized correctly.
The dot position seems being at begin of VRAM (it's to say at begin of drawable image on screen), isn't it ?

**Comment by AmigaIstMiST** [comment]
Hmm, have a look at the 3rd picture, there is a surplus dot _under_ the guru, not on the first position of the drawable area. The behavior is also different between AGA and ECS, like the shifted screen bug.

**Comment by renaudhelias** [comment]
Some display could start at another offset like in CPC, but begin of RAM (used for video, alias VRAM) is still begin of RAM. The better to do for the author here is to isolate this pixel forcing it on or else off during RAM (VRAM) read to find firstly that there is only one address of the VRAM that is concerned here just before display. This way he could, in a first step, capture this bug.

**Comment by renaudhelias** [comment]
It feels perhaps more a "pixel displayed after the last one" defect.

**Comment by AmigaIstMiST** [comment]
To reproduce the bug:
- use ECS or OCS chipset
- use kickstart 3.1 for Amiga 500
- guru somehow :-)
The dot appears in VGA and in SCART configuration.

The dot does *not* appear, if I use kickstart 1.x (strange, isn't it?) and ECS/OCS.
The dot also does not appear, if i use AGA chipset.

**Comment by renaudhelias** [comment]
a beta version is a version no finalized yet (but that does something cool), I think it's the way to go.

**Comment by renaudhelias** [comment]
https://github.com/rkrajnc/minimig-mist/issues/44

**Comment by AmigaIstMiST** [comment]
The dot also appears in 1.2, it was not introduced in the beta version.

**Comment by AmigaIstMiST** [comment]
Fixed in V 1.2.3
