### ISSUE TITLE
minimig_mist_rtg_201006.rbf, Kick1.2 problem ?

### ISSUE THREAD

**Issue by micv2** [mist-devel/mist-binaries#92]
Hello, after the latest minimig_mist_rtg_201006.rbf update, I can no longer start with Kick1.2 (yellow screen). I used Kick1.2 for very old scene demos ADFs. Kick1.3 works, causes image errors in some old demos .. Best regards, MiC

**Comment by robinsonb5** [comment]
The kickstart 1.2 problem has already been identified and fixed - so the next binary release will solve that.

Can you let us know which demos in particular are displaying incorrectly with kick1.3, and what's the last binary release that displayed them correctly?

**Comment by micv2** [comment]
Hi, This intro doesn't work with kick 1.3. it is a known problem. With kick 1.2 you can enjoy it.

http://www.pouet.net/prod.php?which=66562

**Comment by robinsonb5** [comment]
Ah, thank you. (I misunderstood.  I thought that as well as reporting the Kick1.2 problem, you were also reporting something that used to work with Kick1.3 and doesn't any more.)

Kick1.2 will work again in the next binary release.

**Comment by micv2** [comment]
Many Thanks :)

Edited the first link .. "World of Wonders" is correct.

**Comment by gyurco** [comment]
If you set up some slow RAM, it'll work (workaround until the next release).

**Comment by micv2** [comment]
Thanks :)

 
 

Gesendet: Samstag, 10. Oktober 2020 um 16:06 Uhr
Von: "gyurco" <notifications@github.com>
An: "mist-devel/mist-binaries" <mist-binaries@noreply.github.com>
Cc: "micv2" <mic1@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [mist-devel/mist-binaries] minimig_mist_rtg_201006.rbf, Kick1.2 problem ? (#92)


 

If you set up some slow RAM, it'll work (workaround until the next release).
