### ISSUE TITLE
New core Minimig-AGA Gltch & Freezes

### ISSUE THREAD

**Issue by Julitium** [mist-devel/mist-binaries#94]
Hi.

The new Minimig-AGA core produces graphical glitch (Sysinfo) and crashes in games that need decrunch.
It looks like a Chip memory issue.
@gyurco, we need your help. 
I attach an example photo.

Thank you.
![IMG_20201018_152011](https://user-images.githubusercontent.com/20946038/96369819-3348bb00-115c-11eb-9eec-5e49d2716471.jpg)

**Comment by gyurco** [comment]
Is this happen with turbo chip/kick ON, too?

**Comment by Julitium** [comment]
Hi.
Yes. Too

Regards.

**Comment by gyurco** [comment]
And with turbo OFF/Fast RAM OFF/only Chip+SlowRAM?

**Comment by Julitium** [comment]
Turbo OFF / Fast OFF / 2Mb Chip/ 1. 5  Mb Slow.... Works fine. But poor result.

Regards.

**Comment by gyurco** [comment]
Please try this.
[minimig_mist_issu94.zip](https://github.com/mist-devel/mist-binaries/files/5397950/minimig_mist_issu94.zip)

**Comment by Julitium** [comment]
Hi.
Same issue. 
![IMG_20201018_215351](https://user-images.githubusercontent.com/20946038/96378493-93efec00-118c-11eb-96df-154257c3a364.jpg)

**Comment by gyurco** [comment]
And with Turbo ON(Both), but Fast OFF (Only Chip+Slow)?

**Comment by Julitium** [comment]
Turbo On (Both), Chip + Slow on, Fast OFF.
Works Fine. Same poor results. 
![IMG_20201018_223434](https://user-images.githubusercontent.com/20946038/96385131-2e9ef980-1192-11eb-9846-75f42318ec7b.jpg)

**Comment by Julitium** [comment]
Turbo Off , Chip + Slow on, Fast OFF.
Works Fine. Same poor results.
![IMG_20201018_223434](https://user-images.githubusercontent.com/20946038/96385209-b4bb4000-1192-11eb-8d2b-18c8c9965a66.jpg)
Turbo On Both , Chip + Slow on, Fast OFF.
Works Fine. Same poor results. 
![IMG_20201018_223909](https://user-images.githubusercontent.com/20946038/96385228-d4eaff00-1192-11eb-89fa-01cb20e7c382.jpg)

**Comment by gyurco** [comment]
Maybe this one?
[minimig_mist_issu94_2.zip](https://github.com/mist-devel/mist-binaries/files/5398194/minimig_mist_issu94_2.zip)

**Comment by Julitium** [comment]
Same results. No support FastRAM On.

**Comment by Julitium** [comment]
Attached screenshot of the previous version of core in case it would help.
![IMG_20201019_002544](https://user-images.githubusercontent.com/20946038/96387438-31094f80-11a2-11eb-8d40-b609399e9f5e.jpg)

**Comment by Julitium** [comment]
![IMG_20201019_003704](https://user-images.githubusercontent.com/20946038/96387671-323b7c00-11a4-11eb-87e2-e7a59b0b78c5.jpg)
Conditions to Work: changing to previous core and then new core.

**Comment by Julitium** [comment]
Previous version also Fortuitous.

**Comment by gyurco** [comment]
Sorry, I have no idea, and cannot reproduce. If you can upload a hdf image (a not too large one), I can test with that.

**Comment by gyurco** [comment]
Another idea: is this happens with both NTSC and PAL clocks? (force it in mist.ini clock_freq 1/2)

**Comment by Julitium** [comment]
Hi.
I give you a HDD Image to Testing.

[HDD test.zip](https://github.com/mist-devel/mist-binaries/files/5404240/HDD.test.zip)

I will test to change clk_force.

Thanks.

**Comment by gyurco** [comment]
Sorry, but it's unusable.
"Please insert a volume containing LIBS/icon.library in any drive"

**Comment by Julitium** [comment]
[HDD_Test2.zip](https://github.com/mist-devel/mist-binaries/files/5404455/HDD_Test2.zip)
try this.

Kick 3.1

**Comment by Julitium** [comment]
Clock Freq. 0/1/2 same results.

**Comment by gyurco** [comment]
The test image works flawlessly - still no idea.

**Comment by Julitium** [comment]
Uppps.... 
I have reason to think that it is precisely the HDF image that is wrong.
Maybe they mixed several versions.
Tested over others images and Works fine. 

Still Testing. 

Thanks Gyurco.

**Comment by Julitium** [comment]
Confirmed ...
It's image failure.

Sysinfo 4.0 over Personal Image Works great.

Excuse my clumsiness, again you save me. I owe you a few beers.

Thank you very much.

**Comment by gyurco** [comment]
Ah, good.
