### ISSUE TITLE
C64 Tape Bugs. 

### ISSUE THREAD

**Issue by Julitium** [mist-devel/mist-binaries#99]
Hi.
The C64 Core needs an update to the tape routines.
I have detected several pieces of software that do not work, they use the Ocean New Tape 4 loader (the ones listed in the link).

http://www.luigidifraia.com/c64/docs/tapeloaders.html#ocean4

In tests I have done on a C64 with Tapuino, there are some bass pilot tones that do not appear on the Core C64.
I have also detected some US Gold (Line of Fire) game, but I don't know what loader is used. But same case. 
All the best. Thanks.

**Comment by gyurco** [comment]
Try today's release, it loads Lethal Weapon for me.

**Comment by Julitium** [comment]
Hi.
Everything is great. 100% surprised. @gyurco, you are undoubtedly a man of great talent.
Thanks for including the on / off switch in the progress bar (please remember to put it in the CPC core).
Thanks a lot.
All the best.

**Comment by Julitium** [comment]
Hello.

Titles that previously failed now work fine. But I have checked others that now do not work (octoplex from mastertronic for example).
It seems to be when this jumps to the program code, apparently the load in the previous core is the same (but it works). 

Thanks a lot.
Greetings.

**Comment by gyurco** [comment]
Try the attached core, it loads Octoplex. I don't know what other titles should I try.

[C64_mist.zip](https://github.com/mist-devel/mist-binaries/files/6151071/C64_mist.zip)

**Comment by Julitium** [comment]
Hi.
All the tests I am doing are ok. It is at the release level.
I will continue testing.
Thank you very much @gyurco. 
All the best

**Comment by Julitium** [comment]
Hello.
All main tests are Ok for me.
Thank you very much @gyurco. 
All the best.

**Comment by gyurco** [comment]
Just changed a number :)
https://github.com/mist-devel/c64/commit/4325ee6b6872516de9c2e0e438994eb776bc3841
